apiVersion: v1
kind: Service
metadata:
  name: test-data-population-app
  namespace: go-api-practice
spec:
  selector:
    app: test-data-population-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
